version: '3.8'

services:
  # NestJS App Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seoul-meari-app
    restart: unless-stopped
    env_file:
      - .env # .env 파일 사용 (프로젝트 루트에 생성 필요)
    ports:
      - "3000:3000" # Host Port : Container Port
    volumes:
      - .:/usr/src/app # 호스트의 현재 디렉토리와 컨테이너의 작업 디렉토리 연결
      - /usr/src/app/node_modules # node_modules는 호스트와 동기화하지 않음 (성능 이슈 방지)
    command: npm run start:dev # 개발 모드로 실행 (소스코드 변경 시 자동 재시작)
